stages:
  - build
  - test
  - deploy

default:
  tags:
    - docker
    - local
 
build_job:
  stage: build
  script:
    - echo "Compilation..."
 
test_job:
  stage: test
  script:
    - echo "Tests..."

deploy_job:
  stage: deploy
  script:
    - echo "Deployment..."