FROM nginx:latest

WORKDIR /usr/share/nginx/html

RUN apt update
RUN apt install -y git 

RUN rm -rf ./*

RUN git clone https://github.com/withaarzoo/3D-Rotate-Tube.git /usr/share/nginx/html/.

EXPOSE 80

CMD ["nginx","-g","daemon off;"]

#docker build -t site-ines:v4 .

#docker run -d -p 92:80 --name siteland4 site-ines:v4

